# SPDX-FileCopyrightText: The reguloj Authors
# SPDX-License-Identifier: 0BSD

name: REUSE compliance
on:
  pull_request:
    branches: [ main ]
jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v2
